name: Main

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
    env:
      RAILS_ENV: test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Prepare Database
        run: bundle exec rake db:schema:load
        working-directory: test/app
      - name: Run Standard
        run: bundle exec rake standard
      - name: Run Test
        run: bundle exec rake test
